name: WP Plugin Check

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
    paths:
      # Any change to a PHP, JavaScript, CSS/SCSS or Markdown file should run checks.
      - '**.js'
      - '**.php'
      - '**.*css'
      - '**.md'
      # These files configure NPM. Changes could affect the outcome.
      - 'package*.json'
      # These files configure Composer. Changes could affect the outcome.
      - 'composer.*'
      # This file configures ESLint. Changes could affect the outcome.
      - '.eslintrc.json'
      # This file configures Stylelint. Changes could affect the outcome.
      - '.stylelintrc.json'
      # This file configures Markdownlint. Changes could affect the outcome.
      - '.markdownlint.json'
      # This file configures PHPCS. Changes could affect the outcome.
      - 'phpcs.xml.dist'
      # Changes to workflow files should always verify all workflows are successful.
      - '.github/workflows/*.yml'
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  # Runs the WP Plugin Check.
  #
  # Checks from the Plugin Review Team.
  #
  # For the detailed list of checks:
  # - https://wordpress.org/plugins/plugin-check/
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up PHP.
  # - Installs Composer dependencies.
  # - Runs the Plugin Check.
  plugin-check:
    name: Plugin Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@2.32.0
      with:
        php-version: '7.4'
        coverage: none
      env:
        fail-fast: false

    - name: Install Composer dependencies
      uses: ramsey/composer-install@v3
      with:
        composer-options: "--no-dev"

    - name: Copy the plugin files to the plugin check folder, excluding the files on .distignore.
      run: rsync -rc --exclude-from="$GITHUB_WORKSPACE/.distignore" "$GITHUB_WORKSPACE/" translation-tools/ --delete --delete-excluded

    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        build-dir: 'translation-tools'
